### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'FactoryTimestamp')

### ISSUE THREAD

**Issue by marcosbianchi** [timoschlueter/nightscout-librelink-up#95]
Hi,
I get this error running docker variant on my computer (Mac) . Authentication seems to work but then throws  this error reading measurementDate:

![image](https://github.com/timoschlueter/nightscout-librelink-up/assets/12137035/dd2d4949-e203-427e-aca5-196759170361)

Thanks in advance!

**Comment by timoschlueter** [comment]
Hi @marcosbianchi have you tried a different region by setting the environment variable?

**Comment by marcosbianchi** [comment]
Yes, tried changing it to EU but received this:

![image](https://github.com/timoschlueter/nightscout-librelink-up/assets/12137035/3948832c-1ec4-47ac-8b25-b54b32af8300)

**Comment by timoschlueter** [comment]
Okay, looks good. Can you see current measurements in the LibreLink Up app using the same credentials?

**Comment by marcosbianchi** [comment]
Yes, app works fine with those credentials. 

![image](https://github.com/timoschlueter/nightscout-librelink-up/assets/12137035/1ce6eb61-c182-46ed-a9a4-dd933e64c8c0)

**Comment by cjazinski** [comment]
I have the same experience after updating to 2.4.0 due to the librelink update.

**Comment by damianpowell** [comment]
I have this experience too. Yes, I can see readings in the LibreLinkUp app. I'm in the UK using the EU2 region (as advised in the log).

**Comment by aleb** [comment]
According to https://gist.github.com/khskekec/6c13ba01b10d3018d816706a32ae8ab2 [measurementData.connection.glucoseMeasurement](https://github.com/timoschlueter/nightscout-librelink-up/blob/87c4f45cfbcca8e11d0edec2f35349ad66449db8/src/index.ts#L297) represents the last glucose measurement. 

The error can happen when there are no readings whatsoever in LibreLinkUp, or when `glucoseMeasurement` is not passed by the server for whatever reason.

Could probably add some checks to keep retrying instead of crashing the server.

**Comment by timoschlueter** [comment]
More information about crashes have been added to the latest version.
